version: "2"

run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - revive
    - unconvert
    - unparam
    - gosec

  settings:
    errcheck:
      check-type-assertions: true

    govet:
      enable-all: true
      disable:
        - shadow
        - fieldalignment

    revive:
      rules:
        - name: exported
          disabled: true
        - name: package-comments
          disabled: true

    gosec:
      excludes:
        - G304
        - G306

formatters:
  enable:
    - gofmt
    - goimports
